{"uuid": "4c7092e1-60cd-46be-8e23-51a35a33b46f", "children": ["12ebb163-b0c7-4b64-b7f2-06866000e188"], "befores": [{"name": "db", "status": "broken", "statusDetails": {"message": "ValueError: port should be of type int\n", "trace": "  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/conftest.py\", line 87, in db\n    return MysqlUtils(host, port, user, password, db)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/utils/mysql_utils.py\", line 7, in __init__\n    self.conn = pymysql.connect(host=host,\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pymysql/connections.py\", line 290, in __init__\n    raise ValueError(\"port should be of type int\")\n"}, "start": 1656777759470, "stop": 1656777759470}], "start": 1656777759470, "stop": 1656777759560}